#!/bin/sh
mkdir -p /etc/shadowsocks-libev
uci -q get shadowsocks-libev.easy >/dev/null || {
	uci -q batch <<-EOF
		set shadowsocks-libev.easy=easy
		set shadowsocks-libev.easy.enabled='0'
		set shadowsocks-libev.easy.mode='bypass'
	EOF
	uci -q commit shadowsocks-libev
}
/etc/init.d/shadowsocks-libev enable >/dev/null 2>&1 || true
/etc/init.d/rpcd reload
exit 0
